language: rust
matrix:
  include:
    - rust: nightly
    - rust: beta
    - rust: stable

cache:
  apt: true
  directories:
    - target/debug/deps
    - target/debug/build

script:
  - cargo build
  - cargo test
env:
  global:
    - ENCRYPTION_LABEL: "927b4e4f8874"
    - COMMIT_AUTHOR_EMAIL: "julius@nauk.io"

after_success:
  - '[ $TRAVIS_PULL_REQUEST = false ] && [ $TRAVIS_RUST_VERSION = stable ] && { [ "$TRAVIS_TAG" != "" ] || [ "$TRAVIS_BRANCH" == "master" ]; } && ./.travis/docs.sh'
